name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - run: rustup update 1.64 --no-self-update && rustup default 1.64
    - run: cargo build
    - run: cargo test
